export const journeyPara1 = 'The game of Life is the best VRMMORPG (Virtual Reality-Massively Multiplayer online playing Game) out there. There are 8 billion players, millions of square miles of explorable area with a cosmic region if you have enough of the game currency and resources and an infinite customizable system to suit your player’s persona. Players are randomly spawned to a family clan and assigned a status, nationality, name, and appearance. The situation of a player’s spawn determines the difficulty of playability of the game for the player. This is how I view life.'
export const journeyPara2 = 'Although this mentality seems like I’m detached from reality to some, it’s very easy for someone to get overwhelmed after the dot com bubble or 2008: warfare has evolved to the bleeding edge, markets are unstable, Russia and China are in a race to become the next global superpower against the United States, and our views are constantly changing even if they are damaging society. But often, I’d like to think of it as a natural disruption in a system that needs maintenance. History teaches us that civilization is weak and requires constant rebuilding. Where there’s a bug, there will be a developer debugging the system and a bottleneck will require more computational power.'
export const journeyPara3 = 'I didn’t always think this way. It wasn’t until I started coding and learning physics, that I started to look at things more analytically. The first principle is taking all the high-level complexities and breaking them down into their low-level fundamental truths. With this approach I got better at problem-solving, understanding people, and video games. After seeing the results, I wanted to apply this methodology to other things. I picked up the electric guitar, drawing, and my health; I was able to learn numerous chords through intense finger fretting practice, I was able to draw portraits I could show to people, and I started feeling better about my physical appearance. This sort of approach is what makes the grind enjoyable: It’s high effort and high reward, yet I’m not satisfied with my current skill level.'

export const mantrasPara1 = 'The game of life is more about the dynamics and gameplay rather than the rewards. If the gameplay were bad, people would stop playing. Different players will enjoy different features, and they may not agree with what other players do, yet I indulge in the things that it has to offer. The item shop is vast and full of exciting things like cars, clothing, properties, food, entertainment, etc., so I would like to be rich. My ideal character would be jacked, have a ton of tattoos, drive fast cars, have a hot wife, and have multiple properties around the world. While this is only the superficial side of myself, I want to be deeper.'
export const mantrasPara2 = 'I want to be someone who doesn’t fold under pressure, is reliable, a role model, is always learning new things, is happy and egotistical, intelligent, and creative, sinful and living life, malleable in the presence of smart people, resilient, innovative, an explorer, artist, entrepreneur, engineer, adaptable, and healthy.'
export const mantrasPara3 = 'To get to that point, I must live by certain virtues. I am living in Zen, working anywhere, expanding consciousness, breaking the ice, inspiring generations, becoming a piece of Michelangelo, using everything to my advantage, mastering my craft, and automating the mundane while enjoying the rest.'

export const future = 'I will keep my goals the same. As long you know where you want to go, you’ll figure out the path to get there. Although I will stay critiquing the flaws in the game of life, I can only fix things in my control. I want to level up by striving to become better than who I was last week. My story will be written by me only, and my player customized by me. I will grow my friends list so I can play co-op with others. The limit doesn’t exist for me as I will continue to keep playing the game of life'

